name: 'check'
on: pull_request
jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Output Format
        run: echo "::add-matcher::.github/check_php_code.json"
      - name: Log info
        run: echo '"info message" on src/test.php(3,1)'
      - name: Log warning
        run: echo '"not warning message" on src/test.php(3,1)'
      - name: Log error
        run: echo '::error::"error message" on src/test.php(3,1)'
      - name: Log debug
        run: echo '::debug::"debug message" on src/test.php(3,1)'
